### ISSUE TITLE
Support for large messages

### ISSUE THREAD

**Issue by ploeh** [GreanTech/Qaiain#4]
Various queue systems have message size limits. Azure Queues, for example, has a size limit of 64 kB.

Qaiain should support emails bigger than 64 kB. Some emails might, in themselves, have enough content to exceed the 64 kB limit, but if they contain attachments, they could easily do so.

It should be possible to use Qaiain with a 'pointer message':
1. Write the actual email message content to file or BLOB storage.
2. Send a message over the queue that points to the BLOB.
3. When Qaiain has handled the message, delete the BLOB.

Due to the non-transactional nature of some queues (e.g. Azure storage queues), there's a risk that the BLOB will be orphaned. In order to prevent too many orphaned files or BLOBs, each message should have only a single BLOB associated. If the email contains multiple items (one or more attachments, as well as the message itself), it should be packaged into a single BLOB or file. ZIP comes to mind...

The pointer message may have a format like this:

``` XML
<email-reference>
  <email-data-address>http://blobs.foo.bar/baz/qux</email-data-address>
</email-reference>
```

**Comment by ploeh** [comment]
While the parsing part of this enhancement seems clear, we also need to figure out a BLOB format. Should we rely on a simple ZIP BLOB?

From .NET, it looks as though we can use the types in the [System.IO.Compression](http://msdn.microsoft.com/en-us/library/vstudio/System.IO.Compression.aspx) namespace to create ZIP archives, and extract contents again from the archives. However, I have no experience with these types, so the following questions arise:
- Are there any practical issues with the System.IO.Compression types that I don't know about, because I haven't used them, or will they fit the requirements presented above?
- Is the format supported by System.IO.Compression interoperable? The BLOBs should be writable by various clients, including, perhaps, clients running on Node.js, .NET, (JVM, Erlang, Ruby, Python, etc...?)

**Comment by moodmosaic** [comment]
Hm... How about using gzip? [Maybe it's more common](http://superuser.com/a/146758) on Unix-like systems.

In .NET, the _System.dll_ assembly contains the [GZipStream](http://msdn.microsoft.com/en-us/library/vstudio/system.io.compression.gzipstream.aspx) class which makes it possible to create gzip files without referencing the _System.IO.Compression.FileSystem.dll_ assembly (required for .Zip, I think).

I created an _xunit.xml.gz_ from _xunit.xml_ on my machine using the following sample code:

``` f#
open System.IO
open System.IO.Compression

let compress (file : FileInfo) = 
    use readStream  = file.OpenRead()
    use writeStream = 
        new GZipStream(
            File.Create(file.FullName + ".gz"), 
            CompressionMode.Compress)
    readStream.CopyTo(writeStream)
```

Node.js seems to support [gzip](http://en.wikipedia.org/wiki/Gzip) through the built-in [Zlib](http://nodejs.org/api/zlib.html) module:

``` javascript
var fs = require('fs');
var zlib = require('zlib');

fs.createReadStream('xunit.xml.gz')
  .pipe(zlib.createGunzip())
  .pipe(fs.createWriteStream('xunit_unzip.xml'));
```

So, as it looks like, gzip files created in .NET can be opened from Node.js applications.

**Comment by ploeh** [comment]
Looks good. How about the other way around?

Qaiain is always going to be the reader, but there could potentially be many different writers. Can e.g. a Node.js application write a file that Qaiain can read with GZipStream?

**Comment by moodmosaic** [comment]
The opposite seems to be working also.

---

FTR, I created a _sample.js_ file with the following code:

``` javascript
var fs = require('fs');
var zlib = require('zlib');

fs.createReadStream('xunit.xml')
  .pipe(zlib.createGzip())
  .pipe(fs.createWriteStream('xunit.xml.gz'));
```

Run as Node.js application with:

```
$ node sample.js
// -> xunit.xml.gz is created (assuming xunit.xml file exists).
```

And then I used the following sample code to read the newly created gzip file:

``` f#
open System.IO
open System.IO.Compression

let decompress (inputFile : FileInfo) = 
    use readStream = 
        new GZipStream(inputFile.OpenRead(), CompressionMode.Decompress)
    let outputPath = 
        inputFile.FullName.Remove(
            inputFile.FullName.Length - inputFile.Extension.Length)
    use writeStream = File.Create(outputPath)
    readStream.CopyTo(writeStream)

FileInfo("xunit.xml.gz") |> decompress
```

**Comment by ploeh** [comment]
@moodmosaic You are indispensable :)

Thank you for researching this; it seems to be a viable direction to take.

**Comment by moodmosaic** [comment]
> The pointer message may have a format like this:
> 
> ```
> <email-reference>
>   <email-data-address>http://blobs.foo.bar/baz/qux</email-data-address>
> </email-reference>
> ```

How about just `data-address` instead of `email-data-address`?

**Comment by ploeh** [comment]
That would probably be fine as well :)

**Comment by moodmosaic** [comment]
Should we close this issue? (Is there anything else left?)
